from registry.saas.hand-china.com/hap-cloud/base:latest

#作者
MAINTAINER weibaoer <yanhh.@qq.com>

ADD ./Exam1-1.0-SNAPSHOT.jar Exam1.jar

ADD ./start.sh start.sh

RUN chmod a+x start.sh

ENTRYPOINT ["./start.sh"]
